# Cirrus CI configuration for FreeBSD custom image builder

freebsd_version_matrix:
  - "13.2"
  - "14.0"
arch_matrix:
  - "amd64/amd64"
  - "arm64/aarch64"
flavor_matrix:
  - "desktop"
  - "poudriere"

task:
  name: Build FreeBSD Images
  persistent_worker:
    labels:
      jail: freebsd
  matrix:
    freebsd_version: $freebsd_version_matrix
    arch: $arch_matrix
    flavor: $flavor_matrix
  env:
    FREEBSD_VERSION: $freebsd_version
    FREEBSD_ARCH: $arch
    FREEBSD_FLAVOR: $flavor
  script: |
    if [ "$CIRRUS_PR" != "" ]; then
      echo "Building for PR #$CIRRUS_PR (branch: $CIRRUS_BRANCH)";
    else
      echo "Building for branch $CIRRUS_BRANCH";
    fi
    id
    bash -x ./make.iso.with.installer.sh
    mkdir -p artifacts
    mv *.img artifacts/FreeBSD-${FREEBSD_VERSION}-RELEASE-${FREEBSD_ARCH}-${FREEBSD_FLAVOR}.img
  artifacts:
    path: artifacts/*.img

release_task:
  only_if: $CIRRUS_BRANCH == 'main'
  name: Release Images
  persistent_worker:
    labels:
      jail: freebsd
  env:
    GH_TOKEN: $GH_TOKEN
  install_script:
    - pkg install -y gh cocogitto
  script: |
    for flavor in desktop poudriere; do
      if cog bump --auto ${flavor}-install/; then
        VERSION=$(cog get-version ${flavor}-install/)
        echo "Version: ${VERSION}"
        echo "moving artifacts"
        mv artifacts/*-${flavor}.img artifacts/FreeBSD-${FREEBSD_VERSION}-${FREEBSD_ARCH}-${flavor}-${VERSION}.img
        gh release create "${flavor}-v${VERSION}" \
          --title "${flavor} v${VERSION}" \
          --notes "$(cog changelog --at ${flavor}-install/v${VERSION})" \
          artifacts/FreeBSD-${FREEBSD_VERSION}-${FREEBSD_ARCH}-${flavor}-${VERSION}.img
      fi
    done
  artifacts:
    path: artifacts/*.img
