# Cirrus CI configuration for FreeBSD custom image builder
freebsd_instance:
  image_family: freebsd-14-2

task:
  name: Build FreeBSD Images
  matrix:
    freebsd_version: $freebsd_version_matrix
    arch: $arch_matrix
    flavor: $flavor_matrix
  env:
    matrix:
      FREEBSD_VERSION: "13.5"
      FREEBSD_VERSION: "14.3"
    matrix:
      FREEBSD_ARCH: "amd64/amd64"
      FREEBSD_ARCH: "arm64/aarch64"
    GH_TOKEN: $GH_TOKEN
  script: |
    sh -x ./make.iso.with.installer.sh
  artifacts:
    path: artifacts/*.img
