version: 2.1

parameters:
  freebsd-versions:
    type: string
    default: "13.2,14.0"
  architectures:
    type: string
    default: "amd64/amd64,arm64/aarch64"

orbs:
  gh: circleci/github-cli@2

executors:
  linux-release:
    machine:
      image: ubuntu-2204:current
  freebsd-builder:
    machine:
      image: freebsd-13.2:current

commands:
  setup-release:
    steps:
      - run:
          name: Install required tools
          command: |
            sudo apt-get update
            sudo apt-get install -y curl wget
            curl -L https://github.com/cocogitto/cocogitto/releases/latest/download/cocogitto-x86_64-unknown-linux-gnu.tar.gz | sudo tar xz -C /usr/local/bin

jobs:
  build-freebsd-images:
    parameters:
      freebsd-version:
        type: string
      arch:
        type: string
      flavor:
        type: string
    executor: freebsd-builder
    steps:
      - checkout
      - setup-release
      - run:
          name: Build FreeBSD image
          command: |
            export FREEBSD_VERSION=<< parameters.freebsd-version >>
            export FREEBSD_ARCH=<< parameters.arch >>
            ./make.iso.with.installer.sh
            mkdir -p artifacts
            mv "${WORK_DIR}"/*.img artifacts/FreeBSD-<< parameters.freebsd-version >>-RELEASE-<< parameters.arch >>-<< parameters.flavor >>.img
      - persist_to_workspace:
          root: artifacts
          paths:
            - "*.img"

  release:
    executor: linux-release
    steps:
      - checkout
      - attach_workspace:
          at: ./artifacts
      - gh/setup
      - run:
          name: Create release with Cocogitto
          command: |
            # Check for version bump in both directories
            for flavor in desktop poudriere; do
              if cog bump --auto ${flavor}-install/; then
                VERSION=$(cog get-version ${flavor}-install/)
                echo "Version: ${VERSION}"
                echo "moving artifacts"
                mv ./artifacts/*-${flavor}.img ./artifacts/FreeBSD-<< parameters.freebsd-version >>-<< parameters.arch >>-${flavor}-${VERSION}.img
                # Create GitHub release
                gh release create "${flavor}-v${VERSION}" \
                  --title "${flavor} v${VERSION}" \
                  --notes "$(cog changelog --at ${flavor}-install/v${VERSION})" \
                  ./artifacts/FreeBSD-<< parameters.freebsd-version >>-<< parameters.arch >>-${flavor}-${VERSION}.img
              fi
            done

workflows:
  build-and-release:
    jobs:
      - build-freebsd-images:
          matrix:
            parameters:
              freebsd-version: ["13.2", "14.0"]
              arch: ["amd64", "arm64"]
              flavor: ["desktop", "poudriere"]
      - release:
          requires:
            - build-freebsd-images
          filters:
            branches:
              only: main
